[package]
name = "bodhi"
description = "bodhi REST API client"
license = "MIT OR Apache-2.0"

version = "0.0.6"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["api-bindings"]
keywords = ["fedora", "bodhi", "REST", "client"]
repository = "https://github.com/ironthree/bodhi-rs"

[dependencies]
failure = "^0.1"
fedora = "^0.0.6"
reqwest = "^0.9"
retry = "^0.5"
serde = { version = "^1.0", features = ["derive"] }
serde_repr = "^0.1.5"
serde_json = "^1.0"
