[package]
name = "bodhi"
description = "bodhi REST API client"
license = "MIT OR Apache-2.0"

version = "0.0.8"
edition = "2018"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
readme = "README.md"
categories = ["api-bindings"]
keywords = ["fedora", "bodhi", "REST", "client"]
repository = "https://github.com/ironthree/bodhi-rs"

[features]
default = []
debug = []

[dependencies]
failure = "^0.1.6"
reqwest = "^0.9.24"
retry = "^0.5.1"
serde_repr = "^0.1.5"
serde_json = "^1.0.44"

[dependencies.fedora]
version = "^0.0.7"
#path = "../fedora-rs"
#features = ["debug"]

[dependencies.serde]
version = "^1.0.103"
features = ["derive"]
