[package]
name = "bodhi"
description = "bodhi REST API client"
license = "MIT OR Apache-2.0"

version = "0.0.0"
edition = "2018"

authors = ["Fabio Valentini"]
readme = "README.md"
categories = ["api-bindings"]
keywords = ["fedora", "bodhi", "REST", "client"]
repository = "https://github.com/ironthree/bodhi-rs"


[dependencies]
reqwest = "^0.9.12"
serde = "^1.0.89"
serde_derive = "^1.0.89"


[profile.release]
lto = true

